"use client";
import { useRef, useState } from "react";

export function SizzleReel() {
  const ref = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(false);

  return (
    <div className="rounded-2xl border border-nv-border bg-nv-surface overflow-hidden">
      <div className="grid md:grid-cols-[2fr_1fr]">
        <div
          className="relative aspect-video bg-black cursor-pointer group"
          onClick={() => {
            const v = ref.current;
            if (!v) return;
            if (v.paused) {
              v.play().catch(() => undefined);
              setPlaying(true);
            } else {
              v.pause();
              setPlaying(false);
            }
          }}
        >
          <video
            ref={ref}
            src="/sizzle.mp4"
            muted
            playsInline
            preload="metadata"
            className="absolute inset-0 w-full h-full object-cover"
            onEnded={() => setPlaying(false)}
          />
          {!playing && (
            <div className="absolute inset-0 flex items-center justify-center bg-black/40 transition group-hover:bg-black/30">
              <div className="w-20 h-20 rounded-full bg-nv-green flex items-center justify-center">
                <svg
                  viewBox="0 0 24 24"
                  fill="black"
                  className="w-8 h-8 ml-1"
                  aria-hidden
                >
                  <path d="M8 5v14l11-7z" />
                </svg>
              </div>
            </div>
          )}
        </div>
        <div className="p-8 flex flex-col justify-between gap-6">
          <div>
            <div className="text-xs uppercase tracking-wider text-nv-green font-mono mb-3">
              33-sec montage
            </div>
            <h3 className="text-2xl font-bold mb-3">
              Eleven brands, one click.
            </h3>
            <p className="text-sm text-nv-muted leading-relaxed">
              Three seconds from each render, stitched into a single sizzle
              reel. Every clip generated by the agent — no human touched the
              frames after the URL.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-3 text-xs font-mono">
            <Pill label="brands" value="11" />
            <Pill label="duration" value="0:33" />
            <Pill label="cost" value="$0" />
            <Pill label="wall time" value="~24m" />
          </div>
        </div>
      </div>
    </div>
  );
}

function Pill({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border border-nv-border bg-black/30 px-3 py-2">
      <div className="text-base text-nv-green font-bold">{value}</div>
      <div className="text-[10px] uppercase tracking-wider text-nv-muted mt-0.5">
        {label}
      </div>
    </div>
  );
}
